### ISSUE TITLE
Errors during yarn start

### ISSUE THREAD

**Issue by zntb** [huiruo/cryptocurrency-trading#1]
Errors when starting yarn in the web folder:

ERROR in src/common/input/InputAddon.tsx:26:13
TS2551: Property 'roundedLeftMedium' does not exist on type 'AtomicProps'. Did you mean 'roundedLeftMD'?
    24 |     if (placement === Placement.start) {
    25 |       attrs.borderLeft = 1
  > 26 |       attrs.roundedLeftMedium = true
       |             ^^^^^^^^^^^^^^^^^
    27 |     }
    28 |
    29 |     if (placement === Placement.end) {

ERROR in src/common/input/InputAddon.tsx:31:13
TS2551: Property 'roundedRightMedium' does not exist on type 'AtomicProps'. Did you mean 'roundedRightMD'?
    29 |     if (placement === Placement.end) {
    30 |       attrs.borderRight = 1
  > 31 |       attrs.roundedRightMedium = true
       |             ^^^^^^^^^^^^^^^^^^
    32 |     }
    33 |   }
    34 |   return (

Failed to parse source map from 'C:\xampp\htdocs\cryptocurrency-trading-main\apps\web\node_modules\@ebay\nice-modal-react\src\index.tsx' file: Error: ENOENT: no such file or directory, open 'C:\xampp\htdocs\cryptocurrency-trading-main\apps\web\node_modules\@ebay\nice-modal-react\src\index.tsx'

**Comment by huiruo** [comment]
fixed, thanks
